### ISSUE TITLE
Not possible to copy the files into Yaml configuration.

### ISSUE THREAD

**Issue by Fatalmose** [cRemE-fReSh/BRiO-WiL-Integration-for-Home-Assistant#1]
Hello,

When I want to copy past your files into the Yaml configuration I get an error statement.

" Unable to read from the browser's clipboard. Please make sure * you have granted access for this website to read from the clipboard. "

How can I solve this.
Thanks for the reply.

Regards.
`
JS.

**Comment by cRemE-fReSh** [comment]
Hi @Fatalmose,

the reported issue is not related to this solution but an issue of the configuration of your browser/computer.
Please search the internet for solutions for your issue.

Kind regards
CF

**Comment by Fatalmose** [comment]
Hello CF.

I solved the problem by using command + c and command + v to integrate your
files into configuration.yaml.
At the last line of the Node-Red integrations i get following error.
" Can not read a block mapping entry , a multiline key may not be an
implicit key "

Regards.

JS.

Le lun. 26 août 2024 à 11:39, cRemE-fReSh ***@***.***> a
écrit :
