### ISSUE TITLE
Error statement after integration Node-Red lines

### ISSUE THREAD

**Issue by Fatalmose** [cRemE-fReSh/BRiO-WiL-Integration-for-Home-Assistant#2]
Hello,

After copying the Node-Red files into configuration.yaml i get following error at the last line.

" Can not read a block mapping entry , a multiline key may not be an implicit key "

Regards.

JS. Fatal Mose

**Comment by cRemE-fReSh** [comment]
Hi,
node-red files have to be imported in node-red but should not be copied to the yaml file.
Kind regards.

**Comment by Fatalmose** [comment]
Hello.

Ok…
Thanks for the reply.
This is the reason why I did…
Integration
<https://github.com/cRemE-fReSh/BRiO-WiL-Integration-for-Home-Assistant#integration>

The integration consists of two elements: Node-RED flow and a few inputs,
that have to be added to the configuration.yaml.

Home Assistant is new to me so I still have to learn a lot.

Thanks for your understanding.
Regards.

JS.

Le jeu. 5 sept. 2024 à 23:56, cRemE-fReSh ***@***.***> a
écrit :

**Comment by Fatalmose** [comment]
Hello.

So if I got the message wright….
I have to install the Node-Red add-on.
Copy your Node-Red files into it.
Copy the input files into configuration.yaml.
And restart HA.

Regards.

JS.

**Comment by Fatalmose** [comment]
Those who do not feel the need to help others should not be on GitHub.
